cloud_skill_mani_in_pasta_homepage:
    path:     /hello/{name}
    defaults: { _controller: CloudSkillManiInPastaBundle:Default:index }
    
cloud_skill_mani_in_pasta_registrazione:
    pattern:  /register.{_format}
    defaults: { _controller: CloudSkillManiInPastaBundle:Registrazione:registrazione, _format: 'json' }
    requirements: 
      _method: POST  
      
cloud_skill_mani_in_pasta_activate:
    pattern:  /activate.{_format}
    defaults: { _controller: CloudSkillManiInPastaBundle:Registrazione:activate, _format: 'json' }
    requirements: 
      _method: PUT  
      
cloud_skill_mani_in_pasta_login:
    pattern:  /login.{_format}
    defaults: { _controller: CloudSkillManiInPastaBundle:Login:login, _format: 'json' }
    requirements: 
      _method: POST  
